#!/bin/zsh

#### Function based abbres

# Return the glyph from given NerdFont code
function glyph(){
    echo -ne "\u$1" | xclip -selection primary
    notify-send "Glyph $(xclip -o) was added to the clipboard" &> /dev/null
}
# Creates a directory and moves into it
function mkcd(){
    mkdir $1 && cd $1    
}

#### Folder abbres

abbr dl="cd ~/Downloads"
abbr doc="cd ~/Documentos"
abbr dbx="cd ~/Dropbox"
abbr grf="cd ~/.config/groff"
abbr gal="cd ~/.scripts/gen-abbres"
abbr mp="cd ~/MyProjects"
abbr dev="cd ~/dev"
abbr pyd="cd ~/dev/python"
abbr jsd="cd ~/dev/js"
abbr untd="cd ~/dev/Unity"
abbr gdtd="cd ~/dev/godot"
abbr untd="cd ~/dev/unity"
abbr rstd="cd ~/dev/rust"
abbr hskd="cd ~/dev/haskell"
abbr cppd="cd ~/dev/cpp"

#### Config files abbres

abbr dmit="nvim ~/.doom.d/init.el"
abbr dmcf="nvim ~/.doom.d/config.el"
abbr dmpkg="nvim ~/.doom.d/packages.el"
abbr xmbl="nvim ~/.config/xmobar/laptop.config"
abbr xmbd="nvim ~/.config/xmobar/laptop.config"
abbr xmnrc="nvim ~/.xmonad/xmonad.hs"
abbr pcmcf="nvim ~/.config/picom/picom.conf"
abbr zrc="nvim ~/.zshrc"
abbr vrc="nvim ~/.vimrc"
abbr nvrc="nvim ~/.config/nvim/init.vim"
abbr frc="nvim ~/.config/fish/config.fish"
abbr txcf="nvim ~/.config/tmux/tmux.conf"
abbr bsprc="nvim ~/.config/bspwm/bspwmrc"
abbr i3cf="nvim ~/.config/i3/config"
abbr sxhrc="nvim ~/.config/sxhkd/sxhkdrc"
abbr pbcf="nvim ~/.config/polybar/config"
abbr pbsh="nvim ~/.config/polybar/launch.sh"
abbr ctcf="nvim ~/.config/compton/compton.conf"
abbr pcmcf="nvim ~/.config/picom/picom.conf"
abbr rgcf="nvim ~/.config/ranger/rc.conf"
abbr ktcf="nvim ~/.config/kitty/kitty.conf"
abbr rfcf="nvim ~/.config/rofi/config.rasi"
abbr nfcf="nvim ~/.config/neofetch/config.conf"
abbr dtrc="nvim ~/.config/dunst/dunstrc"
abbr nbcf="nvim ~/.newsboat/config"
abbr nburl="nvim ~/.newsboat/urls"
abbr nmrc="nvim ~/.config/neomutt/neomuttrc"
abbr als="nvim ~/MyProjects/abbres/abbres"
abbr fbs="nvim ~/MyProjects/abbres/folder-base"
abbr cfbs="nvim ~/MyProjects/abbres/config-base"
abbr cmbs="nvim ~/MyProjects/abbres/command-base"
abbr fsbs="nvim ~/MyProjects/abbres/fish-base"
abbr zbs="nvim ~/MyProjects/abbres/zsh-base"
abbr lgbs="nvim ~/MyProjects/abbres/log-base"

#### Command abbres

abbr nv="nvim"
abbr sz="source ~/.zshrc"
abbr sf="source ~/.config/fish/config.fish"
abbr pc="sudo pacman"
abbr pci="sudo pacman -S"
abbr pcr="sudo pacman -R"
abbr pcu="sudo pacman -Syyu"
abbr yi="yay -S"
abbr yr="yay -R"
abbr yu="yay -Syyu --aur"
abbr sctl="sudo systemctl"
abbr gst="git status --short"
abbr ga="git add"
abbr gaf="git add -f"
abbr gd="git difftool"
abbr gr="git remove"
abbr gc="git commit"
abbr gp="git push"
abbr mv="mv -i"
abbr cp="cp -i"
abbr rm="rm -i"
abbr ctb="crontab -e"
abbr z="zathura"
abbr eop="sudo eopkg"
abbr mkdir="mkdir -p"
abbr ls="ls --color --group-directories-first -a"
abbr yu="yay -Syyu --aur"
abbr yi="yay -S"
abbr yr="yay -R"
abbr tx="tmux -f ~/.config/tmux/tmux.conf"
abbr svu="playerctl -p spotify volume +0.05"
abbr svd="playerctl -p spotify volume -0.05"
abbr sc="run-fzf scripts"
abbr dv="run-fzf dev"
abbr dc="run-fzf documents"
abbr img="run-fzf images"
abbr dls="run-fzf downloads"
abbr proc="ps aux | grep"
abbr prop-class="xprop | grep WM_CLASS | awk '{print \$4}' | sed 's/\"//g' | xclip -selection primary | notify-send 'xprop' 'Class copied to clipboard'"
