#            _              
#           | |             
#    _______| |__  _ __ ___ 
#   |_  / __| '_ \| '__/ __|
#    / /\__ \ | | | | | (__ 
#   /___|___/_| |_|_|  \___|
#
#   ________________________
#
# 
#
# >>> This file should be at $HOME folder or symlinked to it <<<
# 
#
#
# Image settings for neofetch running on terminal startup
#imageSource=~/Imagens/ilya-kuvshinov-catears_edit_resized.png
#imageSize=500px
#neofetch --kitty --size $imageSize  --source $imageSource

export PS1='%{^[[01;38;05;214;48;05;123m%}%m%{^[[0m%} '

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Ignore node_modules folders on fuzzy finding FZF
export FZF_DEFAULT_COMMAND='ag --nocolor --ignore node_modules -g ""'

export PATH=~/.scripts/bin:$PATH
export PATH=/snap/bin:$PATH
export PATH=~/.local/bin:$PATH
export PATH=~/.gem/ruby/2.6.0/bin:$PATH
export TERMINAL=/usr/bin/kitty

export PAGER=most
# Set vim as default editor
VISUAL=vim; export VISUAL EDITOR=vim; export EDITOR

TMOUT=1

TRAPALRM() {
    zle reset-prompt
}

#ZSH_THEME="agnoster"
ZSH_THEME="powerlevel9k/powerlevel9k"

# Loading Oh-My-ZSH plugins
plugins=(
  git
  tmux
  vi-mode
)

# Load Antigen config
source $HOME/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle heroku
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found
antigen bundle chrissicool/zsh-256color
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle momo-lab/zsh-abbrev-alias

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Load the theme.
#antigen theme robbyrussell
#antigen theme commanderkelso/oh-my-zsh-gruvbox-powerline-theme gruvbox-powerline
antigen theme agnoster

# Tell Antigen that you're done.
antigen apply

# Load Powerline9k custom segments
source $HOME/.config/zsh/p9k-segments

# Load Powerlevel9k settings
source $HOME/.config/zsh/p9krc

# Load Oh-My-Zsh
source $ZSH/oh-my-zsh.sh

# Loads alias file
source $HOME/.config/zsh/aliases
