#!/bin/bash

folder_file=$HOME/.scripts/gen-aliases/folder-base
config_file=$HOME/.scripts/gen-aliases/config-base
command_file=$HOME/.scripts/gen-aliases/command-base
zsh_base=$HOME/.scripts/gen-aliases/zsh-base
fish_base=$HOME/.scripts/gen-aliases/fish-base

zsh_file=$HOME/.config/zsh/aliases
fish_file=$HOME/.config/fish/abbreviations

rm $HOME/.config/zsh/aliases
rm $HOME/.config/fish/abbreviations

echo "# vi: syntax=bash" | tee -a $zsh_file $fish_file
echo -e "\n# Folder aliases\n" >> $zsh_file
sed "s/\s*#.*$//;/^\s*$/d" $folder_file | tee >(awk '{print "alias "$1"=\"cd "$2"\""}' >> $zsh_file) \
                            >(awk '{print "abbr "$1" \"cd "$2"\""}' >> $fish_file)
echo -e "\n# Config files aliases\n" | tee -a $zsh_file $fish_file
sed "s/\s*#.*$//;/^\s*$/d" $config_file | tee >(awk '{print "alias "$1"=\"vim "$2"\""}' >> $zsh_file) \
                            >(awk '{print "abbr "$1" \"vim "$2"\""}' >> $fish_file)
echo -e "\n# Command aliases\n" | tee -a $zsh_file $fish_file
sed "s/\s*#.*$//;/^\s*$/d" $command_file | tee >(awk '{print "alias "$1"=\""$2" "$3"\""}' >> $zsh_file) \
                            >(awk '{print "abbr "$1" \""$2" "$3"\""}' >> $fish_file)
echo -e "\n# Function based aliases\n" | tee -a $zsh_file $fish_file
sed "1d" $fish_base >> $fish_file
sed "1d" $zsh_base >> $zsh_file
