#!/bin/bash

# Check if battery is charging or not
MODE="$(acpi -b | sed "s/,//g" | awk '{print ""$3""}')"
# Get the battery % to show appropriate icon
PERCENT="$(acpi -b | sed "s/,//g" | awk '{print ""$4""}' | sed "s/%//g")"
# Set charging icon
c_icon=""

# Select battery icon based on %
if [ $PERCENT -lt 10 ] ; then
    icon=""
fi
if [ $PERCENT -ge 10 ] ; then
    icon=""
fi
if [ $PERCENT -ge 20 ] ; then
    icon=""
fi
if [ $PERCENT -ge 30 ] ; then
    icon=""
fi
if [ $PERCENT -ge 40 ] ; then
    icon=""
fi
if [ $PERCENT -ge 50 ] ; then
    icon=""
fi
if [ $PERCENT -ge 60 ] ; then
    icon=""
fi
if [ $PERCENT -ge 70 ] ; then
    icon=""
fi
if [ $PERCENT -ge 80 ] ; then
    icon=""
fi
if [ $PERCENT -ge 90 ] ; then
    icon=""
fi
if [ $PERCENT -eq 100 ] ; then
    icon=""
fi

# If charging, show charging icon, else shows selected icon
if [ "$MODE" = "Charging" ] 
then
    notify-send "$(acpi -b | sed "s/,//g" | awk -v x=$c_icon '{print x " "$3" - "$4" - Time remaining: "$5""}')" 
else
    notify-send "$(acpi -b | sed "s/,//g" | awk -v x=$icon '{print x " "$3" - "$4" - Time remaining: "$5""}')" 
fi

