#!/usr/bin/env sh

# i3blocks mail module.
# Displays number of unread mail and an loading icon if updating.
# When clicked, brings up `neomutt`.
# Original script: Luke Smith

pass mutt-wizard-g_barbafh >/dev/null

MAILCOUNT=$(du -a ~/.local/share/mail/g_barbafh/INBOX/new/* 2>/dev/null | sed -n '$=')

# MAILCOUNT=$(echo $(du -a ~/.local/share/mail/g_barbafh/INBOX/new/ | sed -n '$='))
# MAILCOUT="$(du -a ~/.local/share/mail/g_barbafh/INBOX/new/ | sed -n '$=')$(cat /tmp/imapsyncicon_$USER 2>/dev/null)"

if [ $MAILCOUNT > 0 ] ; then
    echo "%{T5}  %{T9}$MAILCOUNT"
else
    echo "%{T5}  "
fi
