#!/usr/bin/env sh

# i3blocks mail module.
# Displays number of unread mail and an loading icon if updating.
# When clicked, brings up `neomutt`.
# Original script: Luke Smith

case $BLOCK_BUTTON in
	1) "$TERMINAL" -e neomutt ;;
	2) setsid mailsync >/dev/null & ;;
	3) pgrep -x dunst >/dev/null && notify-send "📬 Mail module" "\- Shows unread mail
- Shows 🔃 if syncing mail
- Left click opens neomutt
- Middle click syncs mail" ;;
esac

MAILCOUT="$(du -a ~/.local/share/mail/g_barbafh/INBOX/new/* 2>/dev/null | sed -n '$=')$(cat /tmp/imapsyncicon_$USER 2>/dev/null)"

if [ $MAILCOUNT > 0 ] ; then
    echo $MAILCOUNT
else
    echo "0"
fi
