#!/bin/bash

response=""
# Try to get metadata from spotify
state=$(playerctl -p spotify metadata 2>&1 | grep -c "xesam") 
# If the status is 0 (Spotify is running), gets the information
# else, tells that Spotify is not running
if [ $state -eq 0 ]; then
    response=""
else
    song=$(playerctl -p spotify metadata xesam:title)
    artist=$(playerctl -p spotify metadata xesam:artist)
    response=" Spotify | $artist - $song "
fi

echo "$response"
