#!/bin/bash

export PATH="$PATH:$HOME/.local/bin/"

#USER=$(whoami)
#PID=$(pgrep -u $USER gnome-session)
#export DBUS_SESSION_BUS_ADDRESS=$(grep -z DBUS_SESSION_BUS_ADDRESS /proc/$PID/environ|cut -d= -f2-)

files=($HOME/Imagens/Wallpapers/*)
image="$(printf "%s\n" "${files[RANDOM % ${#files[@]}]}")"
gsettings set org.gnome.desktop.background picture-uri file://$image
feh --bg-scale $image
# wal -i $image 

# . "${HOME}/.cache/wal/colors.sh"

# if hash dunst 2>/dev/null; then
#   killall dunst
#   dunst \
#     -frame_width 0 \
#     -lb "${color0}" \
#     -nb "${color0}" \
#     -cb "${color0}" \
#     -lf "${color7}" \
#     -bf "${color7}" \
#     -cf "${color7}" \
#     -nf "${color7}" &
# fi

echo "Wallpaper changed!"
notify-send "Random Wallpaper" "Wallpaper changed!"
