#!/bin/bash


killall polybar

primary=$(bspc query -M -m --names)

if [ $primary == "LVDS1" ] || [ $primary == "VGA1" ] ; then
  polybar complete-laptop 2>~/.logs/polybar.log &
else
  polybar complete 2>~/.logs/polybar.log &

fi

notify-send -i "Polybar" "Status bar reloaded"

