#!/bin/bash

ICON=~/Imagens/icones/refresh-2-xxl.png

killall polybar
notify-send -i $ICON "Polybar" "Status bar reloaded"

primary=$(bspc query -M -m --names)

if [ $primary == "LVDS1" ] || [ $primary == "VGA1" ] ; then
  polybar complete-laptop &
else
  polybar complete &
fi

