#!/bin/bash


killall polybar
notify-send -i "Polybar" "Status bar reloaded"

primary=$(bspc query -M -m --names)

echo "Polybar queried"

if [ $primary == "LVDS1" ] || [ $primary == "VGA1" ] ; then
  polybar complete-laptop &
else
  polybar complete &
fi

