#!/bin/bash

FILE=~/Documentos/Favoritos/twitch-favorites
ICON=~/Dropbox/imagens/icones/twitch-purple-logo.png

CHOICE=$(cat $FILE | rofi -dmenu -i -p "Twitch Favorites")

if [ "$CHOICE" != "" ] ; then
  notify-send -i $ICON "Streamlink" "Loading channel $CHOICE..."
  OUTPUT=$(streamlink -p mpv twitch.tv/$CHOICE best)

  COUNT=$(echo $OUTPUT | grep -c "error")

  if [ $COUNT -gt 0 ] ; then
    notify-send -i $ICON "Streamlink" "$CHOICE is offline"
  fi
fi

