#!/bin/bash

mode=$1
folder=/home/$USER

case $mode in
    scripts)
        folder+=/.scripts
        ;;
    dev)
        folder+=/dev
        ;;
    documents)
        folder+=/Documentos
        ;;
    images)
        folder+=/Imagens
        ;;
    downloads)
        folder+=/Downloads
esac

du -a --exclude={*node_modules,*venv,*.git,*python3*} $folder/* | 
    awk '{print $2}' | fzf | xargs -r $EDITOR
