#!/bin/bash

mode=$1
echo $mode
folder=/home/$USER

if [ $mode == scripts ]; then
    folder=/home/$USER/.scripts
    echo $folder
fi
if [ $mode == dev ]; then
    folder=/home/$USER/dev
    echo $folder
fi

du -a $folder/* | awk '{print $2}' | fzf | xargs -r $EDITOR 2>/dev/null
