#!/bin/bash

FILE=""
BROWSER=qutebrowser
ICON=~/Dropbox/imagens/icones/qutebrowser.png

# TODO: Use global variables for both url files
if [ "$1" = "-f" ] || [ "$1" = "--favorites" ] ; then
  FILE=$BROWSER_FAVORITES
else
  FILE=$BROWSER_MOST_USED
fi

OPTION=$(sort $FILE | awk -F'"' '$0=$2' | rofi -dmenu -i -l 30 -p "Web")

if [ "$OPTION" != "" ] ; then

  URL=$(grep "$OPTION" $FILE | sed -e "s/\".*\"//g" -e "s/ //g")

  notify-send -i $ICON "Qutebrowser" "Opening page '$OPTION'" && qutebrowser $URL &

fi
