#! /bin/sh

xsetroot -cursor_name left_ptr & 

random-wallpaper

killall polybar 
~/.config/polybar/launch.sh &

killall sxhkd 
sxhkd &

bspc config border_width         1
bspc config window_gap          12
bspc config border_radius       10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc monitor -d 1 2 3 4 5 6 7 8 9 0
# bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc rule -a Code desktop=^1
bspc rule -a Firefox desktop=^2
bspc rule -a Brave-browser desktop=^2
bspc rule -a Epiphany desktop=^2
bspc rule -a qutebrowser desktop=^2 follow=on

# Epiphany installed websites
bspc rule -a epiphany-amazon-brasil-775f4cd0af28ccf52cfce19ba063c2c16dca2d79 desktop=^2

# Requires spotifywm-git to define WM_CLASS before the window opens.
# Without it, bspwm doesn't have the WM_CLASS from spotify when the window opens,
# making the rule ineffective
bspc rule -a Spotify desktop=^3

bspc rule -a discord desktop=^4
bspc rule -a UnityHub desktop=^5
bspc rule -a Unity desktop=^5
bspc rule -a obs desktop=^6
bspc rule -a Aseprite desktop=^7
bspc rule -a krita desktop=^7
bspc rule -a Blender desktop=^7
bspc rule -a Steam desktop=^8
bspc rule -a mpv desktop=^10 follow=on

bspc rule -a Peek state=floating
bspc rule -a Yad state=floating

udiskie &

dunstwal &

setxkbmap -option caps:escape

picom --experimental-backends

export TEST="jajaja"

export TWITCH_FAVORITES=~/Documentos/twitch-favorites

xset -dpms s off
