#! /bin/sh

# Checks which monitor is primary to setup either desktop or laptop monitors
# Assumes the following monitors:
# - DVI-D-0 and HDMI-0 for Desktop
# - LVDS1 and VGA1 for Laptop

primary=$(bspc query -M -m --names)
count=$(bspc query -M | wc -l)

if [[ $primary == "LVDS1" ]]; then
  if [[ $count -gt 1 ]]; then
    # HDMI to the left, Mounted monitor to the bottom right
    xrandr --output LVDS1 --mode 1366x768 --pos 1920x312 --rotate normal --output VGA1 --primary --mode 1920x1080 --pos 0x0 --rotate normal
    bspc monitor VGA1 -d 1 2 3 4 5 6 7 8 9 I
    bspc monitor LVDS1 -d 10
  else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 I 10
  fi
else 
  if [[ $primary == "DVI-D-0" ]]; then
    if [[ $count -gt 1 ]]; then
      xrandr --output HDMI-0 --mode 1366x768 --rotate normal --output DVI-D-0 --primary --mode 1920x1080 --rotate normal --right-of HDMI-0
      # bspc monitor HDMI-0 -s DVI-D-0
      bspc monitor DVI-D-0 -d 1 2 3 4 5 6 7 8 9
      bspc monitor HDMI-0 -d 10
    else
      bspc monitor -d 1 2 3 4 5 6 7 8 9 10
    fi
  fi
fi

dunstwal &

random-wallpaper

sxhkd_running=$(proc sxhkd | grep " sxhkd " | wc -l)
if [ $sxhkd_running -gt 0 ] ; then
    killall sxhkd 
fi
sxhkd &

xsetroot -cursor_name left_ptr & 

# picom --experimental-backends

killall udiskie
udiskie &

xset -dpms s off

dropbox &

bspc config border_width         2
bspc config window_gap          8 
bspc config border_radius       8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc rule -a Code desktop=^1
bspc rule -a Anki desktop=^1
bspc rule -a firefox desktop=^2
bspc rule -a Brave-browser desktop=^2
bspc rule -a Epiphany desktop=^2
bspc rule -a Thunderbird desktop=I
# bspc rule -a qutebrowser desktop=^2 follow=on

# Requires spotifywm-git to define WM_CLASS before the window opens.
# Without it, bspwm doesn't have the WM_CLASS from spotify when the window opens,
# making the rule ineffective
bspc rule -a Spotify desktop=^3

bspc rule -a discord desktop=^4
bspc rule -a UnityHub desktop=^5
bspc rule -a Unity desktop=^5
bspc rule -a obs desktop=^6
bspc rule -a Aseprite desktop=^7
bspc rule -a krita desktop=^7
bspc rule -a Blender desktop=^7
bspc rule -a Steam desktop=^8
bspc rule -a mpv desktop=^10 follow=on

bspc rule -a Godot desktop=^5 state=floating
bspc rule -a Godot_Engine desktop=^5 state=floating
# Rust project, change the name or add more as needed
bspc rule -a observer_test desktop=^10 state=floating 

bspc rule -a dotnet state=floating
bspc rule -a Peek state=floating
bspc rule -a Yad state=floating
bspc rule -a Gnome-calculator state=floating

eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

# ~/.config/polybar/launch.sh &
reload-polybar
