#! /bin/sh


xsetroot -cursor_name left_ptr & 

killall polybar 
~/.config/polybar/launch.sh &

killall sxhkd 
sxhkd &

bspc monitor -d code browser music chat ws5 ws6 ws7 ws8 ws9 ws10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Code desktop=^1
bspc rule -a Firefox desktop=^2
bspc rule -a Brave-browser desktop=^2

# Requires spotifywm-git to define WM_CLASS before the window opens.
# Without it, bspwm doesn't have the WM_CLASS from spotify when the window opens,
# making the rule ineffective
bspc rule -a Spotify desktop=^3

bspc rule -a discord desktop=^4
bspc rule -a UnityHub desktop=^5
bspc rule -a Unity desktop=^5
bspc rule -a obs desktop=^6
bspc rule -a Aseprite desktop=^7
bspc rule -a Krita desktop=^7
bspc rule -a Blender desktop=^7
bspc rule -a Steam desktop=^8

bspc rule -a Peek state=floating

random-wallpaper

udiskie &

dunstwal &

setxkbmap -option caps:escape

picom --experimental-backends
