#!/bin/bash

OPTIONS='Cancelar\nDesligar\nReiniciar\nSuspender\nSair\n'
CONFIRM='Não\nSim'

CHOICE=$(echo -e $OPTIONS | rofi -dmenu -i -p "Sistema")

if [ "$CHOICE" != "Cancelar" ] && [ "$CHOICE" != "" ] ; then

    OUTPUT=$(echo -e $CONFIRM | rofi -dmenu -i -p "Tem certeza?")
    if [ "$OUTPUT" = "Sim" ] ; then
        case $CHOICE in
            "Sair")
                bspc quit
                ;;
            "Reiniciar")
                reboot
                ;;
            "Desligar")
                shutdown -h now
                ;;
            "Suspender")
                systemctl suspend
                ;;
        esac
    fi
fi
exit 0
