#!/bin/zsh

folder_file=$HOME/.folder_base
config_file=$HOME/.config_base
command_file=$HOME/.command_base
misc_file=$HOME/.misc_base
zsh_file=$HOME/.aliases
fish_file=$HOME/.config/fish/config.fish

rm $HOME/.aliases
rm $HOME/.config/fish/config.fish

echo "# vi: syntax=zsh" >> $zsh_file
echo "# vi: syntax=fish" >> $fish_file
echo -e "\n# Folder aliases\n" >> $zsh_file
sed "/^#/d" $folder_file | tee >(awk '{print "alias "$1"=\"cd "$2"\""}' >> $zsh_file) \
                            >(awk '{print "abbr "$1" \"cd "$2"\""}' >> $fish_file)
echo -e "\n# Config files aliases\n" | tee -a $zsh_file $fish_file
sed "/^#/d" $config_file | tee >(awk '{print "alias "$1"=\"vim "$2"\""}' >> $zsh_file) \
                            >(awk '{print "abbr "$1" \"vim "$2"\""}' >> $fish_file)
echo -e "\n# Command aliases\n" | tee -a $zsh_file $fish_file
sed "/^#/d" $command_file | tee >(awk '{print "alias "$1"=\""$2" "$3"\""}' >> $zsh_file) \
                            >(awk '{print "abbr "$1" \""$2" "$3"\""}' >> $fish_file)
echo -e "\n# Function based aliases\n" | tee -a $zsh_file $fish_file
sed "1d" $misc_file | tee -a $zsh_file $fish_files
