#!/bin/bash

# Try to get metadata from spotify
playerctl -p spotify metadata &> /dev/null
# If the status is 0 (Spotify is running), gets the information
# else, tells that Spotify is not running
if [ $(echo $?) -eq 0 ] ; then
    song=$(playerctl -p spotify metadata xesam:title)
    artist=$(playerctl -p spotify metadata xesam:artist)
    response=" Spotify | $artist - $song "
else
    response="Spotify not running"
fi

echo "$response"
